#########################################################################
# Title:            Community: Atlassian-db                             #
# Author(s):        FullCycle                                           #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  postgres:10                                         #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: atlassian-db
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: atlassian-db
    state: absent

- name: Create atlassian-db directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/atlassian-db
    - /opt/atlassian-db/scripts
    - /opt/atlassian-db/data

- name: "Check if atlassian-db sql script file exists"
  stat:
    path: "/opt/atlassian-db/scripts/atlassian.sql"
  register: atlassian-db_sql

- name: "Import sql script file if it doesnt exist"
  template:
    src: atlassian.sql
    dest: /opt/scripts/atlassian.sql
    force: yes
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
  when: not atlassian-db_sql.stat.exists

- name: Create and start container
  docker_container:
    name: atlassian-db
    image: postgres:10
    pull: yes
    published_ports:
      - "5432:5432"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "atlassian-db.{{ user.domain }}"
      VIRTUAL_PORT: "5432"
      LETSENCRYPT_HOST: "atlassian-db.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/atlassian-db/data:/var/lib/postgresql/data"
      - "/opt/atlassian-db/scripts/atlassian.sql:/docker-entrypoint-initdb.d/atlassian.sql"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - atlassian-db
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
